In [1]:
import pandas as pd
import numpy as np

# Load the Dataset & remove columns after ALP

In [2]:
df = pd.read_csv(r"C:\Users\musab\htOld\2025\dataset\hyperThyroidv1.csv", encoding='latin-1')
# df = pd.read_csv("thyroid.csv")
df = df.loc[:, :"ALP"]

In [3]:
df.head()
data_shape = df.shape

In [4]:
print(list(df.columns))

['HASTANE ADI', 'YA?ADI?I ?L', 'CEP TELF NO', 'HASTA ADI 1.GEL??', '1.geli? tarihi', 'Hasta ADI 2.geli?', 'hasta 2.geli?inintarihi', 'Hasta ADI 3.GEL??', 'hastan?n 3. geli?inin tarihi', 'SEMTOMATIKPHP', 'aphp(asemp)', 'NORMOKALSEM?K', 'sekonder hp', 'Ya?', 'Cinsiyet', 'Boy', 'Kilo', 'BMI', 'Tütün ', '?laç kullan?m? varsa ad?', 'Komorbidite', 'magnezyum', 'alp', 'albümin', 'Serum Ca', '?yonize Ca', 'Serum kreatinin', 'gfr', 'Fosfor', '24 saatlik üriner Ca', '24 saat idrar kreatin', '24 saat idrar fosfor', 'Total protein', 'Trigliseritler', 'LDL', 't.KOLESTROL', 'AST ', 'ALT', 'GGT', 'Kan üre nitrojeni(BUN)', 'Klor', 'Serum 25 hidroksi vitamin D', 'PTH', 'Fraktür var', 'Ürolitiazis var', 'L1 T SKORU', 'L2 T SKORU', 'L3 T SKORU', 'L4 T SKORU', 'L1 Z SKORU', 'L2 Z SKORU', 'L3 Z SKORU', 'L4 Z SKORU', 'Femur boynu z skoru', 'femur boynu t skoru', 'radius z skoru', 'radius t skoru', 'L1-L4 T SKORU', 'FEMUR TOTAL T SKORU', 'L1-L4 Z SKORU', 'FEMUR TOTAL Z SKORU', 'PS?K?ATR?KSEMPTOMVAR', 'KARIN A?RISI', 'Yorgunluk', 'Miyalji', 'Kab?zl?k', 'Uykusuzluk', 'POL?D?PS?', 'Poliüri', 'KAS Güçsüzlük', 'Ba? a?r?s?', 'Bulant?', 'Amnezi', 'Safra ta??', 'Nefrolitiazis', 'Albümine göre düzeltilmi? Ca', 'Serum Ca/P', 'PF index', 'ALP ile birle?tirilmi? CL/PO4', 'Paratiroid sintigrafi', 'Paratiroid SPECT', 'BOYUN USG', '4D BT', '4D MR', 'SPECT+Sestamibi', '99Mtc-MIBI', '99MTC-Sstamibi', '1. AMEL?YAT PATOLOJ? RAPORU', 'ALP']

# Change feature name from turkish to english

In [5]:
column_mapping = {
    "HASTANE ADI": "hospital_name",
    "YA?ADI?I ?L": "living_city",
    "CEP TELF NO": "mobile_phone_number",
    "HASTA ADI 1.GEL??": "patient_name_1st_visit",
    "1.geli? tarihi": "date_of_1st_visit",
    "Hasta ADI 2.geli?": "patient_name_2nd_visit",
    "hasta 2.geli?inintarihi": "date_of_2nd_visit",
    "Hasta ADI 3.GEL??": "patient_name_3rd_visit",
    "hastan?n 3. geli?inin tarihi": "date_of_3rd_visit",
    "SEMTOMATIKPHP": "semtomatikphp",
    "aphp(asemp)": "aphp",
    "NORMOKALSEM?K": "nhph",
    "sekonder hp": "secondary_hp",
    "Ya?": "age",
    "Cinsiyet": "gender",
    "Boy": "height",
    "Kilo": "weight",
    "BMI": "bmi",
    "Tütün ": "tobacco",
    "?laç kullan?m? varsa ad?": "medication_name",
    "Komorbidite": "comorbidity",
    "magnezyum": "magnesium",
    "alp": "alp",
    "albümin": "albumin",
    "Serum Ca": "serum_calcium",
    "?yonize Ca": "ionized_calcium",
    "Serum kreatinin": "serum_creatinine",
    "gfr": "gfr",
    "Fosfor": "phosphorus",
    "24 saatlik üriner Ca": "urinary_calcium_24h",
    "24 saat idrar kreatin": "urinary_creatinine_24h",
    "24 saat idrar fosfor": "urinary_phosphorus_24h",
    "Total protein": "total_protein",
    "Trigliseritler": "Triglycerides",
    "LDL": "ldl_cholesterol",
    "t.KOLESTROL": "total_cholesterol",
    "AST ": "ast",
    "ALT": "alt",
    "GGT": "ggt",
    "Kan üre nitrojeni(BUN)": "bun",
    "Klor": "chlorine",
    "Serum 25 hidroksi vitamin D": "serum_25_hydroxy_vitamin_d",
    "PTH": "pth",
    "Fraktür var": "fracture_present",
    "Ürolitiazis var": "kidney_stones_present",
    "L1 T SKORU": "l1_t_score",
    "L2 T SKORU": "l2_t_score",
    "L3 T SKORU": "l3_t_score",
    "L4 T SKORU": "l4_t_score",
    "L1 Z SKORU": "l1_z_score",
    "L2 Z SKORU": "l2_z_score",
    "L3 Z SKORU": "l3_z_score",
    "L4 Z SKORU": "l4_z_score",
    "Femur boynu z skoru": "femoral_neck_z_score",
    "femur boynu t skoru": "femoral_neck_t_score",
    "radius z skoru": "radius_z_score",
    "radius t skoru": "radius_t_score",
    "L1-L4 T SKORU": "l1_l4_t_score",
    "FEMUR TOTAL T SKORU": "femur_total_t_score",
    "L1-L4 Z SKORU": "l1_l4_z_score",
    "FEMUR TOTAL Z SKORU": "femur_total_z_score",
    "PS?K?ATR?KSEMPTOMVAR": "psychiatric_symptoms_present",
    "KARIN A?RISI": "abdominal_pain",
    "Yorgunluk": "fatigue",
    "Miyalji": "myalgia",
    "Kab?zl?k": "constipation",
    "Uykusuzluk": "insomnia",
    "POL?D?PS?": "polydipsia",
    "Poliüri": "polyuria",
    "KAS Güçsüzlük": "muscle_weakness",
    "Ba? a?r?s?": "headache",
    "Bulant?": "nausea",
    "Amnezi": "amnesia",
    "Safra ta??": "gallstones",
    "Nefrolitiazis": "nephrolithiasis",
    "Albümine göre düzeltilmi? Ca": "corrected_calcium_by_albumin",
    "Serum Ca/P": "serum_calcium_phosphorus_ratio",
    "PF index": "pf_index",
    "ALP ile birle?tirilmi? CL/PO4": "alp_combined_with_cl_po4",
    "Paratiroid sintigrafi": "parathyroid_scintigraphy",
    "Paratiroid SPECT": "parathyroid_spect",
    "BOYUN USG": "neck_ultrasound",
    "4D BT": "4d_ct",
    "4D MR": "4d_mri",
    "SPECT+Sestamibi": "spect_sestamibi",
    "99Mtc-MIBI": "99mtc_mibi",
    "99MTC-Sstamibi": "99mtc_sestamibi",
    "1. AMEL?YAT PATOLOJ? RAPORU": "first_surgery_pathology_report",
    "ALP": "alp_final"
}
df.rename(columns=column_mapping, inplace=True)

df.head()
print(list(df.columns))

['hospital_name', 'living_city', 'mobile_phone_number', 'patient_name_1st_visit', 'date_of_1st_visit', 'patient_name_2nd_visit', 'date_of_2nd_visit', 'patient_name_3rd_visit', 'date_of_3rd_visit', 'semtomatikphp', 'aphp', 'nhph', 'secondary_hp', 'age', 'gender', 'height', 'weight', 'bmi', 'tobacco', 'medication_name', 'comorbidity', 'magnesium', 'alp', 'albumin', 'serum_calcium', 'ionized_calcium', 'serum_creatinine', 'gfr', 'phosphorus', 'urinary_calcium_24h', 'urinary_creatinine_24h', 'urinary_phosphorus_24h', 'total_protein', 'Triglycerides', 'ldl_cholesterol', 'total_cholesterol', 'ast', 'alt', 'ggt', 'bun', 'chlorine', 'serum_25_hydroxy_vitamin_d', 'pth', 'fracture_present', 'kidney_stones_present', 'l1_t_score', 'l2_t_score', 'l3_t_score', 'l4_t_score', 'l1_z_score', 'l2_z_score', 'l3_z_score', 'l4_z_score', 'femoral_neck_z_score', 'femoral_neck_t_score', 'radius_z_score', 'radius_t_score', 'l1_l4_t_score', 'femur_total_t_score', 'l1_l4_z_score', 'femur_total_z_score', 'psychiatric_symptoms_present', 'abdominal_pain', 'fatigue', 'myalgia', 'constipation', 'insomnia', 'polydipsia', 'polyuria', 'muscle_weakness', 'headache', 'nausea', 'amnesia', 'gallstones', 'nephrolithiasis', 'corrected_calcium_by_albumin', 'serum_calcium_phosphorus_ratio', 'pf_index', 'alp_combined_with_cl_po4', 'parathyroid_scintigraphy', 'parathyroid_spect', 'neck_ultrasound', '4d_ct', '4d_mri', 'spect_sestamibi', '99mtc_mibi', '99mtc_sestamibi', 'first_surgery_pathology_report', 'alp_final']

In [6]:
def find_empty_columns(data_frame):
    empty_columns = data_frame.columns[data_frame.isnull().all()]
    return empty_columns


empty_columns = find_empty_columns(df)

if not empty_columns.empty:
    print(f"The empty columns are: {empty_columns}")
else:
    print("No empty columns found.")

The empty columns are: Index(['semtomatikphp', 'urinary_phosphorus_24h',
       'psychiatric_symptoms_present', 'spect_sestamibi'],
      dtype='object')

# Removed Columns

In [7]:
df.drop(columns=[
    'hospital_name', 'living_city', 'mobile_phone_number', 
    'patient_name_1st_visit', 'date_of_1st_visit', 
    'patient_name_2nd_visit', 'date_of_2nd_visit', 
    'patient_name_3rd_visit', 'date_of_3rd_visit'
], inplace=True)

df.drop(columns=['medication_name','comorbidity'], inplace=True)
df.drop(columns=['psychiatric_symptoms_present','urinary_phosphorus_24h', 'spect_sestamibi'], inplace=True)


df.drop(columns=["semtomatikphp"], inplace=True)
df.head()

,aphp,nhph,secondary_hp,age,gender,height,weight,bmi,tobacco,magnesium,...,alp_combined_with_cl_po4,parathyroid_scintigraphy,parathyroid_spect,neck_ultrasound,4d_ct,4d_mri,99mtc_mibi,99mtc_sestamibi,first_surgery_pathology_report,alp_final
0,NaN,NaN,EVET/ILACABAGLI,NaN,NaN,NaN,NaN,NaN,NaN,1.8,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,EVET/ILACABAGLI,NaN,NaN,NaN,NaN,NaN,NaN,1.8,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68
2,NaN,NaN,EVET/ILACABAGLI,49.0,K,NaN,NaN,NaN,NaN,1.5,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.5
3,NaN,NaN,EVET/ILACABAGLI,NaN,NaN,NaN,NaN,NaN,NaN,1.8,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85
4,NaN,NaN,EVET/ILACABAGLI,34.0,K,NaN,NaN,NaN,NaN,1.81,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Handle Hayit/Evet In target columns

In [8]:
# binary_columns = ['aphp', 'nhph', 'secondary_hp'']

# for column in binary_columns:
#     df[column] = df[column].map({'HAYIR': 0, 'EVET': 1})

# print(df.columns)

for column in ['aphp', 'nhph', 'secondary_hp']:
    unique_vals = df[column].dropna().unique()  # Drop NaN values and get unique ones
    print(f"Column: {column}")
    print(unique_vals)
    print("-" * 30)  # Separator for readability

# Mapping values for 'aphp' column
df['aphp'] = df['aphp'].map({'Asemptomatik': 1, 'EVET': 1}).fillna(0)

# Mapping values for 'nhph' column
df['nhph'] = df['nhph'].map({'nhph(normokals)': 1, 'Normokalsemik': 1, 'HAYIR': 0}).fillna(0)

# Mapping values for 'secondary_hp' column
df['secondary_hp'] = df['secondary_hp'].map({
    'EVET/ILACABAGLI': 1, 
    'EVET/DV?T EKS?KL???': 1, 
    'EVET/?LAÇ SEKONDER': 1, 
    'EVET/?LAÇ VE DV?T EKS?KL???': 1, 
    'Sekonder hp': 1, 
    'sekonder hp': 1, 
    'HAYIR': 0
}).fillna(0)

df.head()

for column in ['aphp', 'nhph', 'secondary_hp']:
    unique_vals = df[column].dropna().unique()  # Drop NaN values and get unique ones
    print(f"Column: {column}")
    print(unique_vals)
    print("-" * 30)  # Separator for readability

Column: aphp
['Asemptomatik' 'EVET']
------------------------------
Column: nhph
['HAYIR' 'nhph(normokals)' 'Normokalsemik']
------------------------------
Column: secondary_hp
['EVET/ILACABAGLI' 'EVET/DV?T EKS?KL???' 'EVET/?LAÇ SEKONDER'
 'EVET/?LAÇ VE DV?T EKS?KL???' 'HAYIR' 'Sekonder hp' 'sekonder hp']
------------------------------
Column: aphp
[0. 1.]
------------------------------
Column: nhph
[0. 1.]
------------------------------
Column: secondary_hp
[1. 0.]
------------------------------

In [9]:
df.head
#df.to_excel('hyperThyroidv1Result.xlsx', index=False)

<bound method NDFrame.head of       aphp  nhph  secondary_hp   age gender  height  weight  bmi tobacco  \
0      0.0   0.0           1.0   NaN    NaN     NaN     NaN  NaN     NaN
1      0.0   0.0           1.0   NaN    NaN     NaN     NaN  NaN     NaN
2      0.0   0.0           1.0  49.0      K     NaN     NaN  NaN     NaN
3      0.0   0.0           1.0   NaN    NaN     NaN     NaN  NaN     NaN
4      0.0   0.0           1.0  34.0      K     NaN     NaN  NaN     NaN
...    ...   ...           ...   ...    ...     ...     ...  ...     ...
1664   0.0   0.0           0.0   NaN    NaN     NaN     NaN  NaN     NaN
1665   0.0   0.0           0.0   NaN    NaN     NaN     NaN  NaN     NaN
1666   0.0   0.0           0.0   NaN    NaN     NaN     NaN  NaN     NaN
1667   0.0   0.0           0.0   NaN    NaN     NaN     NaN  NaN     NaN
1668   0.0   0.0           0.0   NaN    NaN     NaN     NaN  NaN     NaN

     magnesium  ... alp_combined_with_cl_po4 parathyroid_scintigraphy  \
0          1.8  ...                      NaN                        0
1          1.8  ...                      NaN                        0
2          1.5  ...                      NaN                        0
3          1.8  ...                      NaN                        0
4         1.81  ...                      NaN                        0
...        ...  ...                      ...                      ...
1664       NaN  ...                      NaN                      NaN
1665       NaN  ...                      NaN                      NaN
1666       NaN  ...                      NaN                      NaN
1667       NaN  ...                      NaN                      NaN
1668       NaN  ...                      NaN                      NaN

      parathyroid_spect neck_ultrasound 4d_ct  4d_mri 99mtc_mibi  \
0                   NaN             NaN   NaN     NaN        NaN
1                   NaN             NaN   NaN     NaN        NaN
2                   NaN             NaN   NaN     NaN        NaN
3                   NaN             NaN   NaN     NaN        NaN
4                   NaN             NaN   NaN     NaN        NaN
...                 ...             ...   ...     ...        ...
1664                NaN             NaN   NaN     NaN        NaN
1665                NaN             NaN   NaN     NaN        NaN
1666                NaN             NaN   NaN     NaN        NaN
1667                NaN             NaN   NaN     NaN        NaN
1668                NaN             NaN   NaN     NaN        NaN

     99mtc_sestamibi first_surgery_pathology_report  alp_final
0                NaN                            NaN        NaN
1                NaN                            NaN         68
2                NaN                            NaN       48.5
3                NaN                            NaN         85
4                NaN                            NaN        NaN
...              ...                            ...        ...
1664             NaN                            NaN        NaN
1665             NaN                            NaN        NaN
1666             NaN                            NaN        NaN
1667             NaN                            NaN        NaN
1668             NaN                            NaN        NaN

[1669 rows x 74 columns]>

# Handling Gender Var/Yok Categorical Values

In [10]:
binary_columns = [
'tobacco',
    "abdominal_pain",
    "fatigue",
    "myalgia",
    "constipation",
    "insomnia",
    "polydipsia",
    "polyuria",
    "muscle_weakness",
    "headache",
    "nausea",
    "amnesia",
    "gallstones",
    "nephrolithiasis",'fracture_present', 'kidney_stones_present'
]
for column in binary_columns:
    unique_vals = df[column].dropna().unique()  # Drop NaN values and get unique ones
    print(f"Column: {column}")
    print(unique_vals)
    print("-" * 30)



import pandas as pd

def transform_value(x):
    # If missing or blank, return -1
    if pd.isna(x) or str(x).strip() == "":
        return -1
    # Convert value to lowercase and trim spaces
    s = str(x).strip().lower()
    # If the value equals 'yok', it's 0; otherwise, it's 1
    return 0 if s == "yok" else 1

binary_columns = [
    'tobacco',
    "abdominal_pain",
    "fatigue",
    "myalgia",
    "constipation",
    "insomnia",
    "polydipsia",
    "polyuria",
    "muscle_weakness",
    "headache",
    "nausea",
    "amnesia",
    "gallstones",
    "nephrolithiasis",
    'fracture_present',
    'kidney_stones_present'
]

for col in binary_columns:
    df[col] = df[col].apply(transform_value)

Column: tobacco
['YOK' 'var' 'VAR' 'yok']
------------------------------
Column: abdominal_pain
['VAR' 'var']
------------------------------
Column: fatigue
['var' 'VAR' ' ']
------------------------------
Column: myalgia
['VAR' 'var']
------------------------------
Column: constipation
['YOK']
------------------------------
Column: insomnia
['YOK']
------------------------------
Column: polydipsia
['VAR' 'YOK' '1']
------------------------------
Column: polyuria
['VAR' 'YOK' '1' 'var']
------------------------------
Column: muscle_weakness
['VAR' 'YOK' '1']
------------------------------
Column: headache
['VAR' 'YOK' '1' 'var']
------------------------------
Column: nausea
['VAR' 'var' ' VAR' 'YOK' '1']
------------------------------
Column: amnesia
['VAR' 'YOK' '1']
------------------------------
Column: gallstones
['YOK' 'VAR' 'VAR(?)' 'yok' 'var']
------------------------------
Column: nephrolithiasis
['var' 'VAR']
------------------------------
Column: fracture_present
['YOK' 'VAR' ' ' ' 168.7' 'VAR, TRAVMA ?LE']
------------------------------
Column: kidney_stones_present
['YOK' 'yok']
------------------------------

# Handling Gender Var/Yok Categorical Values

In [11]:
# Define mapping for gender values
gender_mapping = {
    'K': 1, 'KADIN': 1, 'Kad?n': 1, 'Kad?n ': 1, 'kad?n': 1,  
    'E': 0, 'ERKEK': 0, 'Erkek': 0, 'erkek': 0
}

# Apply mapping
df['gender'] = df['gender'].map(gender_mapping)

# Handle missing and invalid values (including '84')
df['gender'] = df['gender'].apply(lambda x: -1 if pd.isna(x) or x not in [0, 1] else x)

unique_vals = df['gender'].dropna().unique()  # Drop NaN values and get unique ones
print(unique_vals)
# Display the resulting DataFrame

[-1.  1.  0.]

# Cleaning Serum Creatinine & Triglycerides

In [12]:
import re

df['serum_creatinine'] = df['serum_creatinine'].astype(str).str.replace(r'\.{2,}', '.', regex=True)

print(df['Triglycerides'].head(50))

def clean_triglycerides(x):
    if isinstance(x, str):
        x = x.strip()
        if x == "":
            return ""
        # Split the string by semicolon
        parts = x.split(';')
        values = []
        for part in parts:
            # Remove non-numeric characters, then strip whitespace
            cleaned = re.sub(r'[^0-9.-]', '', part).strip()
            if cleaned:
                try:
                    values.append(float(cleaned))
                except ValueError:
                    pass
        # Return the highest value found, or an empty string if no valid number is found
        return max(values) if values else ""
    return x

df['Triglycerides'] = df['Triglycerides'].apply(clean_triglycerides)

print(df['Triglycerides'].head(50))

0       66
1       66
2       66
3       66
4       67
5       67
6       67
7       67
8     67.3
9       68
10      68
11      69
12      69
13      69
14      69
15      69
16      69
17      69
18      69
19    69.2
20    69.2
21    69.7
22      70
23      70
24      70
25      70
26    70.2
27      71
28      71
29      71
30    71.3
31    71.6
32    71.9
33    71.9
34      72
35      72
36      72
37      72
38    72.1
39    72.9
40      73
41      73
42      73
43      73
44      73
45      73
46      73
47      73
48      73
49      74
Name: Triglycerides, dtype: object
0     66.0
1     66.0
2     66.0
3     66.0
4     67.0
5     67.0
6     67.0
7     67.0
8     67.3
9     68.0
10    68.0
11    69.0
12    69.0
13    69.0
14    69.0
15    69.0
16    69.0
17    69.0
18    69.0
19    69.2
20    69.2
21    69.7
22    70.0
23    70.0
24    70.0
25    70.0
26    70.2
27    71.0
28    71.0
29    71.0
30    71.3
31    71.6
32    71.9
33    71.9
34    72.0
35    72.0
36    72.0
37    72.0
38    72.1
39    72.9
40    73.0
41    73.0
42    73.0
43    73.0
44    73.0
45    73.0
46    73.0
47    73.0
48    73.0
49    74.0
Name: Triglycerides, dtype: object

# Find Messy data format

In [13]:
columns_to_convert = [
    'bmi', 'magnesium', 'alp', 'albumin', 'ionized_calcium', 'serum_creatinine',
    'phosphorus', 'urinary_calcium_24h', 'urinary_creatinine_24h',
    'ldl_cholesterol', 'ast', 'ggt', 'bun', 'chlorine', 'serum_25_hydroxy_vitamin_d',
    'pth', 'l1_t_score', 'l4_t_score', 'femoral_neck_z_score', 'femoral_neck_t_score',
    'radius_z_score', 'pf_index'
]

for col in columns_to_convert:
    try:
        # Try applying the string methods
        temp = df[col].str.replace(r'[^0-9.-]', '', regex=True).str.strip()
    except Exception as e:
        print(f"Error processing column '{col}': {e}")
        # Loop through values to find a non-string value
        for idx, val in df[col].iteritems():
            if not isinstance(val, str):
                print(f" --> At index {idx}, found non-string value: {val} (type: {type(val)})")
                break

# Clean messy data format

In [14]:
import re

def robust_convert(x):
    # Ensure we work with a string
    if not isinstance(x, str):
        return x
    # Trim whitespace; if the string is empty, leave it empty
    x = x.strip()
    if x == "":
        return ""
    # Split on semicolon to handle multiple values in one cell
    parts = x.split(';')
    values = []
    for part in parts:
        part = part.strip()
        # Replace commas with dots and remove square brackets if present
        part = part.replace(',', '.').strip('[]')
        # Use regex to extract numeric parts (including negatives and decimals)
        found_numbers = re.findall(r'-?\d+(?:\.\d+)?', part)
        for num in found_numbers:
            try:
                values.append(float(num))
            except Exception:
                pass
    # If no valid numbers were found, leave it empty; otherwise, return the maximum value
    return max(values) if values else ""

# List of columns to convert
columns_to_convert = [
    'bmi', 'magnesium', 'alp', 'albumin', 'ionized_calcium', 'serum_creatinine',
    'phosphorus', 'urinary_calcium_24h', 'urinary_creatinine_24h', 'Triglycerides',
    'ldl_cholesterol', 'ast', 'ggt', 'bun', 'chlorine', 'serum_25_hydroxy_vitamin_d',
    'pth', 'l1_t_score', 'l4_t_score', 'femoral_neck_z_score', 'femoral_neck_t_score',
    'radius_z_score', 'pf_index'
]

# Apply the robust conversion function to each column
for col in columns_to_convert:
    df[col] = df[col].astype(str).apply(robust_convert)

# Optionally, print some unique values to check the conversion
for col in columns_to_convert:
    unique_vals = df[col].dropna().unique()
    print(f"Column: {col}")
    print(unique_vals)
    print("-" * 30)

Column: bmi
['' 26.48553975 21.49959688 31.63265306 24.609375 24.00548697 29.96161169
 31.17913832 29.31985649 24.75 34.7 19.6 33.28402367 26.57312925
 33.51458568 31.25 31.76 20.59860803 24.18704649 47.0 32.56188509 26.36
 32.34244946 24.21875 28.16249373 22.40817899 35.05563176 36.41329085
 23.80540166 25.8 43.12908983 22.65625 19.97918835 29.76086271 31.98
 26.86328304 29.2 45.36940687 28.32658037 35.2 33.0 28.2 24.24 31.2 34.4
 23.5 26.9 38.2 32.8 26.2 33.9 36.4 19.0 26.3 24.0 28.3 30.13 30.2 21.2
 30.4 37.2 30.9 19.9 21.3 30.8 43.9 30.3 33.1 32.7 29.6 27.0 19.7 39.2
 20.3 37.3 31.3 38.7 32.1 21.6 24.22 22.8 43.2 31.0 22.7 19.8 38.8 37.8
 41.13 29.3 34.0 27.13 26.7 23.4 28.8 23.19 42.3 42.1 36.3 35.9 30.0 43.6
 43.04 18.5 22.3 26.96 24.8015873 24.6 38.70967742 35.01277966 24.69135802
 35.49168975 22.67995241 29.93759487 23.8 21.36752137 31.60321237
 17.83590963 27.70083102 33.73250126 32.0 31.8 40.0 22.64737696
 23.22543185 30.078125 29.87 30.48668503 30.47052154 27.77777778
 29.74419988 32.19 37.75602259 20.0 31.89 41.1 27.05380277 35.15339664
 32.79194476 38.62590401 26.8 46.6 28.13 24.2 32.5 31.59626039 38.44675125
 30.42663892 31.24499279]
------------------------------
Column: magnesium
[1.8 1.5 1.81 1.82 1.51 1.83 1.84 1.85 1.53 1.55 1.57 1.86 1.87 1.58 1.88
 1.89 1.9 '' 1.62 2.0 1.91 1.92 1.93 1.94 1.95 1.96 1.97 1.98 1.99 2.02
 2.03 2.05 2.06 2.07 1.6 2.08 2.09 2.1 2.11 2.12 2.13 2.14 2.15 2.16 2.17
 2.18 2.19 2.2 2.22 2.23 2.24 2.21 2.25 2.27 2.28 2.29 2.3 2.32 2.34 2.37
 2.41 2.42 2.43 2.45 2.47 2.5 2.52 2.54 2.6 3.04 3.23 3.64 4.05 9.4 0.78
 1.21 1.28 1.29 1.37 1.45 1.46 1.61 1.64 1.65 1.66 1.67 1.69 1.7 1.71 1.73
 1.74 1.75 1.76 1.77 1.78 1.79 2.01 2.04 2.26 2.31 2.33 2.35 2.39 2.44
 2.58 2.59 2.67 2.77 2.9 3.22 3.31 1.01 1.2 1.47 1.68 1.72 2.36 1.63]
------------------------------
Column: alp
[54.0 55.0 55.8 56.0 56.4 57.0 57.6 57.9 58.0 58.1 59.0 59.1 59.3 59.8
 60.0 60.3 61.0 62.0 '' 62.8 63.0 64.0 64.8 64.9 65.0 65.4 65.6 66.0 66.4
 67.0 67.6 67.8 68.0 68.3 68.5 69.0 69.3 69.8 70.0 70.1 70.9 71.0 71.4
 71.6 72.0 72.9 73.0 73.9 74.0 74.3 74.6 74.9 75.0 75.4 76.0 76.1 76.3
 76.5 76.6 76.9 77.0 77.4 77.9 78.0 79.0 79.2 79.5 80.0 81.0 81.4 82.0
 83.0 83.4 83.6 84.0 85.0 85.9 86.0 87.0 88.0 88.4 89.0 89.1 89.2 90.0
 91.0 92.0 93.0 94.0 94.2 95.0 95.8 96.0 96.5 97.0 98.0 99.0 100.0 100.6
 101.0 102.0 103.0 104.0 105.0 106.0 107.0 108.0 109.0 109.7 110.0 110.2
 111.0 112.0 113.0 114.0 115.0 116.0 116.7 117.0 119.0 120.0 121.0 122.0
 123.0 124.0 125.0 126.0 127.0 128.0 129.0 130.0 131.0 132.0 133.0 134.0
 135.0 135.5 136.0 137.0 138.0 141.0 142.0 148.0 151.0 152.0 153.0 154.0
 156.0 160.0 163.0 170.0 172.0 177.0 181.0 187.0 189.0 191.0 192.0 194.0
 202.0 204.7 205.0 206.0 213.0 223.0 234.5 235.0 237.8 243.0 249.0 251.0
 256.0 256.2 260.0 280.0 313.0 320.0 405.0 405.6]
------------------------------
Column: albumin
[4.1 4.9 3.9 3.8 3.5 3.4 3.3 3.1 5.6 5.3 5.1 5.0 4.8 4.7 '' 4.6 4.3 4.57
 4.53 4.5 4.42 4.41 4.4 4.35 4.33 4.2 4.0 3.75 3.7 3.65 3.6 3.2 3.0 2.64
 2.6 2.4 2.1 6.6 6.1 5.8 5.7 5.4 5.2 2.7 2.2 2.0 1.8 1.7]
------------------------------
Column: ionized_calcium
[1.2732 12734.0 1.188 12993.0 1.3051 1.3056 13095.0 1.3129 13129.0 1.3325
 13333.0 13415.0 1.19 13444.0 1.3444 1.3472 1.3562 1.3937 1.3951 1.4003
 1.4016 1.4701 1.44 1.45 1.15 1.16 1.17 1.23 '' 1.3 1.4 13.038 0.97 1.191
 1.24 1.1944 1.29 1.32 1.37 1.39 1.43 1.62 1.78 9.1 9.3 1.2 1.0726 1.0802
 1.1873 1.2053 1.2147 1.2321 1.2343 1.2458 1.2511 1.2543 1.273 1.2778
 1.2873 1.2983 1.3093 1.3159 1.3194 1.3247 1.3333 1.3413 1.3474 1.3611
 1.3752 1.3922 1.4592 1.5159 1.5808 1.5952 1.6111 0.61 0.84 1.05 4.7 85.9
 1.2208 1.21 1.2533 1.26 1.2609 1.2633 1.2244 1.25 1.2829 1.2862 1.2092
 1.2877]
------------------------------
Column: serum_creatinine
[0.6 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 0.71 0.72 0.73 0.74
 0.75 0.76 0.768 0.77 0.78 0.79 0.8 0.81 0.82 0.83 0.84 0.85 0.86 0.87
 0.88 0.89 0.9 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.0 1.01 1.02
 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1 1.12 1.13 1.14 1.15 1.18 1.19 1.21
 1.23 1.24 1.26 1.27 1.28 1.33 1.35 1.37 1.38 1.39 1.41 1.44 1.46 1.47
 1.53 1.59 2.01 2.03 2.1 2.21 2.46 2.55 2.61 2.81 1.22 1.4 1.5 0.5 0.46
 0.52 0.53 0.54 0.55 0.56 0.57 0.58 1.11 1.17 1.2 1.29 1.3 1.31 1.52 1.57
 1.58 1.73 1.86 1.89 2.53 67.8 0.59 '']
------------------------------
Column: phosphorus
[2.72 2.75 2.76 2.77 2.79 2.8 2.81 2.82 2.84 2.85 2.86 2.89 2.9 2.92 2.96
 2.97 2.98 2.99 3.0 3.02 3.06 3.09 3.1 3.12 3.13 3.14 3.15 3.19 3.2 3.22
 3.23 3.26 3.3 3.31 3.32 3.33 3.35 3.36 3.38 3.39 3.4 3.42 3.45 3.49 3.5
 3.51 3.54 3.55 3.57 3.6 3.61 3.64 3.69 3.7 3.72 3.73 3.74 3.79 3.8 3.81
 3.83 3.86 3.9 3.94 3.95 4.0 4.09 4.1 4.2 4.26 4.3 4.39 4.4 4.5 4.6 4.8
 4.81 4.9 468.0 2.2 2.6 2.7 1.8 '']
------------------------------
Column: urinary_calcium_24h
[19.0 124.2 124.7 126.0 127.4 128.0 132.0 133.0 134.0 136.0 138.0 140.0
 142.35 143.0 146.47 148.0 149.0 150.0 154.0 155.0 157.0 158.0 159.0 160.0
 162.0 163.0 164.0 165.0 166.0 168.0 169.0 170.0 171.0 172.4 172.5 173.0
 176.4 178.0 180.0 182.0 182.1 183.72 185.0 186.0 187.0 190.0 191.0 191.6
 193.0 196.0 197.0 201.0 202.8 203.0 204.0 205.9 207.0 210.0 211.0 216.0
 217.0 218.0 219.0 220.0 222.75 225.0 228.0 229.7 234.0 235.0 237.0 239.0
 240.0 246.33 248.4 249.0 250.8 252.0 254.0 255.0 256.0 258.4 259.0 260.0
 262.0 263.0 264.0 265.0 271.0 272.0 273.36 275.0 276.0 278.0 279.0 281.4
 286.0 292.0 294.0 299.0 300.0 300.2 303.0 305.0 306.0 307.0 308.55 309.4
 311.0 313.0 317.0 323.0 324.0 325.0 325.2 327.2 330.0 332.0 335.0 335.36
 336.0 336.6 340.0 341.85 346.15 351.8 352.0 352.5 354.0 365.0 376.0 379.0
 381.0 382.0 390.0 393.0 395.0 406.0 407.0 409.0 411.0 415.0 416.0 417.5
 420.0 425.0 429.0 432.0 436.0 440.0 443.0 450.0 455.0 456.0 459.0 464.0
 475.0 478.0 479.3 492.3 495.0 510.0 528.0 540.0 543.0 570.0 581.0 584.0
 588.0 593.0 594.0 601.0 629.0 654.0 659.0 687.0 693.94 780.0 935.0 21.4
 15.6 '' 110.2 137.5 142.5 201.66 202.5 275.6 306.6 310.5 88.5 123.2 168.2
 234.5 295.8 31.9 39.5 81.6 82.0 89.1]
------------------------------
Column: urinary_creatinine_24h
[1081.0 1083.0 1084.0 1092.0 1102.0 1106.0 1124.0 1125.0 1129.0 1130.7
 1132.5 1132.8 1155.6 1167.0 1178.0 1184.4 1189.0 1197.0 1203.2 1220.0
 1225.6 1260.0 1274.0 1281.7 1292.875 1304.0 1323.28 1329.0 1340.32 1343.7
 1350.0 1366.36 1377.0 1385.0 1390.0 1433.1 1439.0 1460.9 1472.0 1498.0
 1526.0 1533.0 1565.0 1625.0 1872.0 2287.52 2866.75 3361.0 5211.0 353.175
 782375.0 789735.0 918065.0 1051.575 1125.2 1129.26 1144.56 1407.1 1515.12
 1516.07 1621.5 1791.63 2074.59 443.72 448.3 48.85 549.45 552.9 615.25
 622.2 732.7 745.25 820.26 845.12 857.7 877.2 923.5 943.4 994.95 125.0
 1020.39 1083.75 1116.18 1119.6 1126.7 1140.24 1334.88 1334.9 135.05
 1353.8 1371.3 1426.8 1445.7 1800.44 2085.44 2389.9 426.88 569.52 621.04
 720.48 743.05 760.21 778.94 780.5 840.5 849.97 862.73 911.7 936.26 979.5
 '']
------------------------------
Column: Triglycerides
[66.0 67.0 67.3 68.0 69.0 69.2 69.7 70.0 70.2 71.0 71.3 71.6 71.9 72.0
 72.1 72.9 73.0 74.0 75.0 75.5 76.0 76.8 77.0 78.0 79.0 79.9 80.0 81.0
 81.6 81.7 82.0 82.2 82.7 83.0 83.2 84.0 84.2 85.0 85.6 86.0 87.0 87.5
 87.7 87.8 88.0 88.8 89.0 90.0 91.0 91.9 92.0 93.0 93.7 94.0 94.6 95.0
 96.0 97.0 98.0 98.3 98.8 99.0 100.0 101.0 101.1 102.0 103.0 104.0 105.0
 105.4 105.6 106.0 107.0 108.0 108.6 109.0 109.6 110.0 110.5 110.8 111.0
 112.0 112.4 112.7 113.0 114.0 115.0 116.0 116.2 117.0 118.0 119.0 119.4
 120.0 122.0 123.0 124.0 121.0 125.0 126.0 127.0 128.0 128.7 129.0 130.0
 131.0 132.0 133.0 133.5 133.8 134.0 135.0 135.8 136.0 136.1 137.0 138.0
 139.0 140.0 140.6 140.7 141.0 142.0 142.3 143.0 144.0 144.1 145.0 146.0
 147.0 147.3 148.0 148.3 149.0 149.2 149.4 150.0 151.0 152.0 152.9 153.0
 153.9 154.0 155.0 156.0 157.0 158.0 158.1 159.0 160.0 161.0 161.4 161.9
 162.0 163.0 163.1 164.0 164.2 165.0 166.0 167.0 167.6 168.0 170.0 171.0
 171.8 172.0 173.0 174.0 175.0 177.0 178.0 179.0 180.0 183.0 184.0 185.0
 186.0 187.0 189.5 190.0 191.0 193.0 194.0 195.0 197.0 198.0 199.0 201.0
 205.0 206.0 207.0 208.0 210.0 211.0 212.0 212.7 213.0 214.0 214.1 215.0
 216.0 217.0 218.0 219.0 220.0 221.0 221.4 222.8 224.0 225.0 226.0 228.0
 228.9 229.0 231.0 231.6 232.0 233.0 234.0 236.0 240.0 243.0 245.0 246.0
 247.9 250.0 252.0 255.0 257.0 258.0 259.0 262.0 262.8 264.8 266.0 267.0
 272.0 274.5 288.0 289.0 290.8 293.7 296.0 297.0 305.0 312.0 318.0 321.0
 326.0 328.0 334.0 336.0 338.0 347.5 363.0 368.0 382.0 418.0 421.0 456.0
 470.0 484.0 496.0 694.1 752.0 820.0 '' 169.0 100.7 101.2 101.5 104.2
 105.5 106.1 106.6 106.9 107.4 108.5 110.2 116.1 117.2 117.6 118.3 118.5
 119.8 119.9 120.8 122.1 124.2 124.7 125.1 127.1 132.4 132.6 134.9 138.8
 141.2 142.7 144.6 146.7 147.2 147.5 148.8 153.8 154.3 156.9 158.2 160.9
 166.8 168.7 168.9 170.5 170.9 171.3 178.3 178.8 188.5 196.0 206.2 209.9
 219.6 221.5 233.1 236.8 245.8 247.8 260.7 294.3 298.7 319.4 411.5 445.4
 48.3 48.4 51.5 51.6 55.3 57.5 57.7 587.9 60.8 61.4 62.0 64.9 65.7 67.6
 69.9 70.7 72.3 73.1 74.9 76.3 76.5 77.6 809.6 83.6 84.3 89.1 90.9 92.7
 99.4 102.5 107.5 109.7 109.9 126.4 130.3 138.2 151.5 155.5 166.4 176.9
 180.9 188.6 194.6 198.8 202.3 223.5 274.4 319.9 371.3 40.4 46.6 54.1 59.0
 62.4 636.0 64.5 65.4 71.2 78.3 80.2 80.9 85.1 88.3]
------------------------------
Column: ldl_cholesterol
[103.0 103.4 103.8 104.0 104.9 105.0 105.6 106.0 106.4 106.5 106.6 107.0
 107.2 107.3 107.4 107.7 107.8 108.0 108.1 108.5 108.6 108.8 109.0 109.7
 110.0 110.9 111.0 111.3 111.6 112.0 112.3 112.6 112.7 113.0 113.3 113.9
 114.0 114.5 115.0 115.2 115.5 115.9 117.0 117.2 117.3 117.7 118.0 118.3
 118.6 119.0 119.1 120.0 120.4 120.5 121.0 122.0 122.4 123.0 124.0 124.4
 124.7 124.8 125.0 126.0 126.9 127.0 127.2 127.3 128.0 128.3 129.0 129.2
 129.4 129.7 129.8 130.0 130.2 130.5 131.0 131.2 131.5 132.0 132.1 132.5
 132.9 133.0 133.2 133.4 133.7 133.8 133.9 134.0 134.5 134.7 134.9 135.0
 135.3 135.9 136.0 137.0 138.0 138.5 138.7 139.0 139.3 139.6 140.0 140.1
 140.2 140.6 141.0 141.2 141.5 141.6 141.9 142.0 142.7 143.0 143.6 143.9
 144.0 144.1 145.0 146.0 147.0 147.5 147.6 147.8 147.9 148.0 148.3 148.4
 148.5 149.0 149.1 149.5 150.6 150.9 151.0 151.2 152.0 152.4 153.0 154.0
 154.7 154.9 155.0 155.58 156.0 156.3 157.0 157.1 157.3 158.0 158.7 159.0
 159.1 159.3 160.0 160.4 160.7 161.6 161.7 162.0 162.7 163.0 163.2 163.3
 164.3 165.1 165.4 166.0 166.5 167.0 167.2 168.8 169.0 170.0 170.6 170.7
 171.0 174.0 174.6 176.0 176.3 179.0 181.0 171.2 171.4 172.0 173.3 182.0
 184.0 184.3 185.0 185.9 189.9 190.0 191.8 192.3 193.0 194.0 194.1 195.0
 196.0 197.0 199.6 200.0 202.6 202.7 203.0 203.6 205.0 207.4 211.0 212.4
 214.0 219.0 219.3 220.0 221.0 227.4 228.4 229.9 235.0 237.0 238.0 244.0
 245.0 250.0 259.7 268.0 280.0 295.4 297.0 100.8 100.9 101.9 105.2 105.5
 105.82 105.9 106.2 109.1 110.2 111.9 113.1 113.7 114.1 114.7 120.1 121.8
 122.2 123.6 124.2 126.6 127.4 127.5 128.2 128.4 130.1 130.9 132.4 132.8
 133.6 135.5 136.5 136.6 136.7 137.1 137.6 137.8 138.3 142.2 142.9 144.3
 144.8 145.8 146.3 146.4 148.6 150.4 151.4 151.5 151.9 153.4 154.3 155.6
 156.1 158.1 159.8 162.8 164.7 164.9 167.8 167.9 170.1 171.6 172.3 173.0
 173.2 174.4 174.8 180.3 180.6 182.9 185.1 189.0 190.1 192.1 194.9 195.8
 221.2 221.5 226.3 257.1 51.8 59.1 60.4 60.9 63.6 65.8 66.6 67.1 67.5 68.1
 72.1 73.1 73.3 75.3 76.9 77.2 78.3 78.5 78.9 79.5 81.3 82.6 82.8 83.3
 83.4 85.5 85.9 86.0 87.4 89.4 89.5 89.7 90.0 90.7 90.8 90.9 91.3 91.4
 91.8 92.4 93.1 93.9 95.3 96.2 96.9 98.3 99.5 99.9 100.4 103.9 109.3 112.5
 115.3 121.1 125.8 129.6 140.4 146.1 146.5 180.7 186.5 197.4 231.4 231.5
 69.8 71.2 75.8 77.7 79.8 82.7 84.6 86.5 86.8 87.6 96.6 100.3 102.1 102.6
 102.7 103.7 104.3 104.4 106.1 106.22 107.9 109.6 111.1 112.8 112.9 113.5
 114.6 115.4 116.4 116.8 120.7 121.3 122.8 123.2 123.5 123.7 124.1 124.9
 125.4 125.9 126.1 126.3 127.7 127.8 128.1 128.7 131.6 131.9 134.1 134.3
 135.8 136.9 137.9 138.2 140.9 143.5 143.7 144.6 145.4 146.6 148.1 148.7
 153.9 155.9 162.1 164.8 169.9 172.8 173.4 175.3 175.6 176.4 176.7 178.3
 178.6 179.2 180.2 181.8 183.3 188.1 194.7 198.6 199.9 216.6 219.1 221.7
 273.0 353.0 43.4 53.4 59.3 61.8 64.7 66.2 66.7 72.0 80.6 81.1 81.8 83.6
 83.9 85.1 86.2 86.3 89.2 89.9 90.2 90.5 91.5 91.6 92.9 93.2 95.1 95.6
 96.8 97.9 99.1 '']
------------------------------
Column: ast
[12.2 12.4 12.7 12.8 12.9 13.0 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9
 14.0 14.1 14.2 14.3 14.5 14.7 14.8 15.0 15.1 15.4 15.6 15.7 15.8 15.9
 16.0 16.1 16.2 16.4 16.6 16.9 17.0 17.1 17.2 17.5 17.7 17.9 18.0 18.1
 18.3 18.4 18.5 18.6 18.7 18.9 19.0 19.3 19.4 19.5 19.6 20.0 20.3 20.4
 21.0 22.0 22.1 22.4 23.0 24.0 24.9 25.0 25.1 27.0 27.3 28.0 29.0 29.4
 30.0 31.0 32.0 33.0 34.0 35.0 36.0 37.0 38.0 39.0 40.0 41.0 41.5 41.6
 42.0 43.0 43.2 44.0 45.0 46.0 47.0 47.8 48.0 49.0 50.0 51.0 52.0 53.0
 54.0 56.7 57.0 59.0 60.0 61.0 64.0 66.0 69.0 71.0 77.8 80.0 83.0 98.0
 103.0 110.0 23.1 24.1 10.2 11.2 15.2 21.2 16.3 10.5 12.5 9.6 16.7 19.7
 20.7 24.7 22.9 23.9 30.9 '' 10.6 10.7 10.9 11.3 11.4 11.5 11.8 11.9 12.0
 12.1 12.3 12.6 14.4 15.3 15.5 16.5 16.8 17.3 17.4 17.6 17.8 18.8 19.8
 19.9 20.1 20.2 20.5 20.6 21.8 22.2 22.5 22.7 22.8 23.4 23.5 24.8 25.4
 25.7 27.1 29.3 31.3 31.5 35.8 36.5 7.1 8.7 9.3 9.8 31.2 34.7 42.7 43.8
 48.4 87.9]
------------------------------
Column: ggt
['' 11.0 14.8 47.0 20.0 64.0 49.6 12.0 29.0 19.0 15.0 54.1 23.0 31.5 27.0
 13.4 139.8 16.0 16.6 91.0 49.0 19.5 17.6 32.0 36.0 10.0 9.0 13.0 20.7 7.9
 62.0 9.7 14.3 24.0 18.5 37.0 7.0 17.7 31.0 22.0 38.0 53.0 19.4 71.0 51.66
 53.9 18.0 10.7 16.1 8.0 11.4 27.6 45.0 28.0 35.8 21.4 25.0 37.1 16.2 13.7
 17.5 14.7 27.2 51.8 14.0 62.3 12.8 5.0 21.0 20.6 60.0 48.4 19.3 19.9 12.1
 15.8 55.0 30.0 31.2 36.5 12.4 10.4 21.1 62.4 26.0 17.0 50.0 15.6 15.2
 115.3 33.0 9.8 10.3 72.0 46.0 59.0 601.0 148.0 200.0 39.0 97.0 51.0 54.0
 33.9 83.0 48.0 12.5 12.9 35.0 17.2 14.5 30.2 35.6 11.6 9.1 23.4 140.0
 11.1 8.4 49.9 44.7 21.5 39.6 68.0 15.1 65.5 21.3 33.6 27.5 16.3 75.0 23.2
 23.9 14.4 12.6 41.3 42.0 19.6 25.1 34.0 86.0 26.5 13.2 7.1 12.3 156.4
 18.8 43.7 12.2 33.1 41.0 13.5 20.3 9.6 70.0 90.83 35.3 58.6 14.1 95.0
 107.0 15.9 8.5 28.3 117.0 139.6 10.6 96.2 11.05 65.0 174.0 128.0 44.0
 20.2 78.0 82.0 123.0 30.4 57.0 14.9 141.0 52.0 164.0 12.7 26.4 66.2 35.4
 19.7 73.0 78.2 31.6]
------------------------------
Column: bun
[13.0 13.2 13.5 13.6 13.9 13.95 14.0 14.1 14.2 14.33 14.35 14.4 14.61 15.0
 15.13 15.4 15.5 15.6 15.7 16.0 16.29 16.5 16.9 16.96 17.0 17.7 17.757
 18.0 18.5 18.7 19.0 19.1 19.2 19.3 19.51 19.8 20.0 20.2 21.0 21.4 21.7
 21.71 22.0 22.8 23.0 23.19 23.2 23.6 24.0 24.6 24.8 25.0 25.2 25.6 26.0
 26.52 26.6 27.0 27.4 27.8 28.0 28.1 28.25 29.0 29.6 29.8 29.9 30.0 30.5
 31.0 32.0 32.1 33.0 34.0 34.2 35.0 36.0 36.3 37.0 37.7 38.0 39.0 40.0
 40.6 41.0 42.0 42.8 43.0 44.0 45.0 46.0 48.0 49.0 50.0 53.0 54.0 54.6
 59.0 72.0 108.0 113.0 5.42 11.42 10.55 8.57 11.66 5.91 12.21 '' 9.1 18.2
 13.3 15.3 17.03 10.4 17.4 22.4 11.6 14.06 9.7 11.7 13.7 8.8 14.8 16.8
 11.9 15.09 10.11 10.1 10.6 10.7 10.8 11.0 11.1 11.2 11.5 11.8 12.0 12.1
 12.2 12.3 12.4 12.7 13.1 13.4 13.8 14.3 14.7 15.2 15.8 16.1 16.3 16.4
 16.6 17.3 17.8 17.9 18.3 18.37 18.6 19.6 19.63 19.7 19.94 20.6 20.7 21.5
 21.9 22.36 23.7 26.2 28.3 6.1 6.4 6.7 6.9 7.3 7.7 8.0 8.3 8.74 8.9 8.94
 9.0 9.2 9.4 9.41 9.58 9.9 13.68 14.38 14.48 14.65 14.85 15.67 16.54 17.35
 17.54 19.76 22.99 24.37]
------------------------------
Column: chlorine
['' 107.0 104.0 102.0 101.0 106.2 105.8 105.4 106.0 108.0 105.9 105.0
 110.0 103.0 100.9 97.0 104.4 108.9 106.5 104.6 95.2 98.0 108.1 112.2
 107.5 106.6 100.0 112.0 109.0 104.7 100.3 104.5 108.8 85.5 95.0 97.2 98.9
 92.7 104.2 100.7 92.0 100.8 111.0 109.9 99.0 129.6 104.3 103.4 114.3 94.4
 101.5 103.5 102.9 103.6 102.2 102.4 104.9 107.1 98.6 96.0 98.8 100.6]
------------------------------
Column: serum_25_hydroxy_vitamin_d
[9.0 9.1 9.2 9.3 9.4 9.6 9.7 9.8 9.9 10.0 10.08 10.1 10.2 10.3 10.48 10.5
 10.7 10.9 11.0 11.3 11.4 11.5 11.6 11.8 11.9 12.0 12.2 12.5 12.6 12.7
 12.8 12.9 13.0 13.3 13.39 13.4 13.5 13.6 13.7 13.8 13.9 14.0 14.1 14.3
 14.4 14.6 14.8 14.9 15.0 15.2 15.4 15.5 15.6 16.0 16.2 16.3 16.4 16.7
 16.9 17.0 17.1 17.2 17.22 17.4 17.6 17.7 17.8 17.91 18.0 18.1 18.2 18.4
 18.5 18.6 18.7 18.79 18.8 18.9 19.0 19.1 19.2 19.3 19.4 19.5 19.6 19.8
 19.9 20.0 20.3 20.4 20.6 20.7 20.8 20.9 21.0 21.04 21.1 21.3 21.35 21.4
 21.5 21.6 21.7 21.8 21.9 22.0 22.1 22.2 22.3 22.4 22.6 22.8 22.9 23.0
 23.1 23.3 23.4 23.5 23.6 23.7 23.8 23.9 24.0 24.1 24.2 24.3 24.4 24.5
 24.8 24.81 24.9 25.0 25.3 25.4 25.5 25.6 25.62 25.8 26.0 26.1 26.2 26.3
 26.4 26.5 26.6 26.7 26.84 26.9 27.0 27.1 27.2 27.3 27.5 27.6 27.7 28.0
 28.01 28.4 28.8 29.0 29.1 29.2 29.4 29.5 29.6 29.7 29.8 29.95 30.0 30.1
 30.2 30.3 30.4 30.5 30.6 30.65 30.7 30.8 30.9 31.0 31.1 31.2 31.3 31.4
 31.6 31.7 31.8 31.9 32.0 32.1 32.3 32.4 32.6 32.7 32.8 32.9 33.0 33.1
 33.3 33.5 33.7 34.0 34.6 34.7 35.0 35.1 35.2 35.6 35.7 36.0 36.6 36.8
 37.0 37.2 37.4 37.8 37.9 38.0 38.4 39.0 39.1 39.5 39.9 40.0 40.2 40.5
 40.6 40.8 41.0 41.3 41.6 41.9 42.0 43.3 43.7 44.0 44.29 44.5 44.7 44.8
 45.0 45.3 45.5 45.7 45.9 46.0 46.9 47.0 47.4 47.6 48.0 48.2 48.5 48.6
 49.0 49.1 49.5 50.0 50.1 50.42 50.5 51.0 52.1 52.4 53.0 53.4 53.9 54.4
 55.0 55.2 55.6 56.0 57.0 57.6 57.8 59.7 61.8 63.0 63.6 64.9 65.0 65.4
 66.6 67.0 68.92 69.1 70.0 73.0 80.1 80.8 84.0 84.2 85.4 88.3 94.1 100.0
 108.2 129.0 155.0 '' 6.2 6.3 18.3 28.3 16.5 31.5 8.6 11.7 14.7 24.7 25.7
 5.8 7.8 10.8 27.8 15.9 28.9 56.9 10.4 12.3 12.4 14.2 15.1 15.8 16.6 17.5
 22.7 23.2 24.6 25.1 25.2 25.27 27.9 28.1 28.2 28.5 28.7 29.3 29.49 3.7
 33.8 34.8 35.4 36.2 36.4 38.2 39.4 39.6 39.7 4.7 40.4 41.7 42.1 42.4 44.6
 45.2 45.6 46.6 5.3 51.3 52.5 55.8 57.5 57.7 59.1 59.5 6.0 6.1 6.6 6.8
 60.9 7.2 7.4 7.42 71.7 77.8 8.3 8.5 8.8 92.0 160.0 15.45 23.61 28.84 32.2
 32.5 34.1 34.9 36.3 36.9 37.3 38.78 39.3 41.78 41.8 43.1 43.4 44.1 44.3
 48.3 49.8 50.7 51.6 52.3 54.0 54.9 55.9 57.9 61.7 64.1 68.5 8.0 80.0 96.2]
------------------------------
Column: pth
[64.1 64.4 64.6 64.8 64.9 65.0 65.1 65.4 65.5 65.8 65.9 66.0 66.2 66.3
 66.4 66.5 66.6 66.7 67.0 67.1 67.2 67.4 67.42 67.8 68.0 68.4 68.5 68.6
 69.0 69.1 69.2 69.3 69.4 69.7 69.94 70.0 70.2 70.35 70.5 70.7 70.9 71.0
 71.2 71.4 71.7 71.9 72.0 72.3 72.4 72.6 72.7 72.8 73.0 73.3 73.5 73.9
 74.0 74.1 74.5 74.6 74.9 75.0 75.1 75.5 75.6 76.0 76.2 76.3 76.6 76.8
 77.0 77.12 77.3 77.4 77.5 77.6 77.7 78.0 78.1 78.4 78.5 78.6 78.76 79.0
 79.4 79.5 80.0 80.1 80.2 80.3 80.9 81.0 81.4 81.5 81.6 81.9 82.0 82.1
 82.5 82.6 82.8 83.0 83.4 83.5 83.6 83.8 83.9 84.0 84.7 85.0 85.3 85.5
 85.9 86.0 86.53 86.7 87.0 87.3 87.58 87.6 87.9 88.0 88.1 88.11 88.2 88.7
 88.9 89.0 89.3 89.5 89.6 89.9 90.0 90.2 91.0 92.0 92.14 92.3 92.5 92.6
 92.9 93.0 93.1 94.0 94.1 94.2 94.3 94.5 94.6 95.0 95.2 95.3 95.5 95.8
 95.9 96.0 96.2 96.4 96.5 97.0 97.4 97.6 97.9 98.0 98.1 98.2 98.5 98.8
 99.0 99.8 100.0 100.1 100.4 101.0 101.5 101.7 101.9 102.0 102.1 102.7
 103.0 103.1 103.7 104.0 104.4 104.6 104.7 105.0 105.3 105.8 106.0 106.3
 106.8 107.0 108.0 108.6 109.0 109.1 109.4 109.5 110.0 110.2 110.5 110.7
 110.9 111.0 111.7 112.0 112.1 113.0 113.9 114.0 114.2 114.8 115.0 115.1
 115.3 115.4 115.7 115.8 115.9 116.0 116.8 117.0 117.3 118.0 118.2 118.6
 118.9 119.0 119.4 119.8 119.9 120.0 120.7 121.0 121.1 121.2 121.4 121.8
 122.0 122.1 122.7 123.0 123.4 123.5 123.6 123.9 124.0 124.2 124.4 124.6
 125.0 126.0 126.5 126.6 126.9 127.0 127.2 127.3 127.8 127.9 128.0 128.3
 129.0 129.6 129.8 130.0 131.3 132.0 132.2 132.3 132.8 133.0 134.6 135.5
 135.9 136.0 136.1 136.9 137.0 137.2 137.6 138.0 139.0 139.2 139.7 140.0
 141.8 142.0 142.4 142.5 143.0 144.0 145.0 146.0 146.1 147.0 147.5 148.0
 149.0 150.0 150.8 151.0 151.9 152.0 152.7 153.0 153.3 154.0 155.0 155.9
 156.0 156.4 156.7 157.0 158.0 158.7 159.0 160.6 160.7 161.0 162.5 163.0
 164.6 165.0 166.0 166.4 167.0 167.9 168.0 170.0 170.4 170.5 170.6 172.0
 172.7 173.0 174.0 176.0 177.0 177.4 178.0 178.1 179.0 179.8 181.0 182.0

# Display Data

In [15]:
# Define number of rows and columns per group to display
n_rows = 20
group_size = 10

# Loop over columns in groups of 10
for start in range(0, len(df.columns), group_size):
    end = start + group_size
    group_cols = df.columns[start:end]
    print(f"Displaying columns {start+1} to {min(end, len(df.columns))}:")
    print(df.loc[:n_rows-1, group_cols])
    print("=" * 80)

Displaying columns 1 to 10:
    aphp  nhph  secondary_hp   age  gender  height  weight       bmi  tobacco  \
0    0.0   0.0           1.0   NaN    -1.0     NaN     NaN                 -1
1    0.0   0.0           1.0   NaN    -1.0     NaN     NaN                 -1
2    0.0   0.0           1.0  49.0     1.0     NaN     NaN                 -1
3    0.0   0.0           1.0   NaN    -1.0     NaN     NaN                 -1
4    0.0   0.0           1.0  34.0     1.0     NaN     NaN                 -1
5    0.0   0.0           1.0  64.0     1.0   161.0    67.0                 -1
6    0.0   0.0           1.0  67.0     1.0     NaN     NaN                  0
7    0.0   0.0           1.0  69.0     1.0   165.0    69.0                  0
8    0.0   0.0           1.0  74.0     1.0     NaN     NaN                 -1
9    0.0   0.0           1.0  65.0     1.0   153.0    62.0  26.48554       -1
10   0.0   0.0           1.0  38.0     0.0     NaN     NaN                 -1
11   0.0   0.0           1.0   NaN    -1.0     NaN     NaN                 -1
12   0.0   0.0           1.0  46.0     1.0     NaN     NaN                 -1
13   0.0   0.0           1.0   NaN    -1.0     NaN     NaN                 -1
14   0.0   0.0           1.0   NaN    -1.0     NaN     NaN                 -1
15   0.0   0.0           1.0   NaN    -1.0     NaN     NaN                 -1
16   0.0   0.0           1.0   NaN    -1.0     NaN     NaN                 -1
17   0.0   0.0           1.0   NaN    -1.0     NaN     NaN                 -1
18   0.0   0.0           1.0   NaN    -1.0     NaN     NaN                 -1
19   0.0   0.0           1.0   NaN    -1.0     NaN     NaN                 -1

   magnesium
0        1.8
1        1.8
2        1.5
3        1.8
4       1.81
5       1.81
6       1.81
7       1.81
8       1.81
9       1.82
10      1.82
11      1.82
12      1.51
13      1.82
14      1.82
15      1.82
16      1.82
17      1.82
18      1.82
19      1.82
================================================================================
Displaying columns 11 to 20:
     alp albumin  serum_calcium ionized_calcium serum_creatinine   gfr  \
0   54.0     4.1            8.9          1.2732              0.6  79.0
1   54.0     4.1            8.9         12734.0              0.6  80.0
2   54.0     4.9            8.9           1.188              0.6  80.0
3   54.0     4.1            8.9         12993.0              0.6  80.0
4   54.0     4.1            8.9          1.3051              0.6  80.0
5   54.0     4.1            8.9          1.3056              0.6  80.0
6   54.0     4.1            8.9         13095.0              0.6  80.0
7   54.0     4.1            8.9          1.3129              0.6  80.0
8   55.0     4.1            8.9         13129.0              0.6  80.0
9   55.0     3.9            8.9          1.3325              0.6  81.0
10  55.0     3.9            8.9         13333.0             0.61  81.0
11  55.0     3.9            8.9         13415.0             0.61  81.0
12  55.8     4.9            8.9            1.19             0.61  81.0
13  56.0     3.8            8.9         13444.0             0.61  81.0
14  56.0     3.8            8.9          1.3444             0.61  82.0
15  56.0     3.8            8.9          1.3472             0.61  82.0
16  56.0     3.8            8.9          1.3562             0.61  82.0
17  56.0     3.5            8.9          1.3937             0.61  82.0
18  56.0     3.5            8.9          1.3937             0.61  82.0
19  56.4     3.4            8.9          1.3951             0.61  82.0

   phosphorus urinary_calcium_24h urinary_creatinine_24h  total_protein
0        2.72                19.0                 1081.0           7.30
1        2.75               124.2                 1083.0           7.34
2        2.75               124.7                 1084.0           7.40
3        2.76               126.0                 1092.0           7.40
4        2.77               126.0                 1102.0           7.40
5        2.79               127.4                 1106.0           7.40
6        2.79               128.0                 1124.0           7.40
7         2.8               132.0                 1125.0           7.40
8         2.8               133.0                 1129.0           7.40
9         2.8               134.0                 1130.7           7.40
10        2.8               136.0                 1132.5           7.40
11        2.8               138.0                 1132.8           7.40
12        2.8               138.0                 1155.6           7.40
13        2.8               140.0                 1167.0           7.40
14        2.8               140.0                 1178.0           7.41
15        2.8              142.35                 1184.4           7.50
16        2.8               143.0                 1189.0           7.50
17        2.8               143.0                 1197.0           7.50
18        2.8              146.47                 1203.2           7.50
19       2.81               148.0                 1220.0           7.50
================================================================================
Displaying columns 21 to 30:
   Triglycerides ldl_cholesterol  total_cholesterol   ast   alt   ggt   bun  \
0           66.0           103.0              163.0  12.2  10.0        13.0
1           66.0           103.4              163.0  12.4  10.0  11.0  13.0
2           66.0           103.8              163.0  12.7  10.0  14.8  13.0
3           66.0           104.0              163.0  12.8  10.0  47.0  13.0
4           67.0           104.9              163.3  12.8  10.0        13.0
5           67.0           104.9              164.0  12.8  10.0  11.0  13.0
6           67.0           105.0              164.0  12.9  10.0        13.0
7           67.0           105.6              164.0  13.0  10.0  20.0  13.0
8           67.3           106.0              164.0  13.0  10.0  64.0  13.0
9           68.0           106.0              164.0  13.0  10.0        13.0
10          68.0           106.4              164.0  13.0  10.0  49.6  13.0
11          69.0           106.5              165.0  13.0  10.0        13.0
12          69.0           106.6              165.0  13.0  10.0        13.0
13          69.0           106.6              165.0  13.0  10.0  12.0  13.0
14          69.0           107.0              165.0  13.0  10.0  29.0  13.0
15          69.0           107.0              166.0  13.0  10.0        13.0
16          69.0           107.0              166.0  13.0  10.0  19.0  13.0
17          69.0           107.2              166.0  13.0  10.0  15.0  13.0
18          69.0           107.3              166.0  13.0  10.0        13.0
19          69.2           107.4              167.0  13.0  10.1        13.2

   chlorine serum_25_hydroxy_vitamin_d   pth
0                                  9.0  64.1
1     107.0                        9.0  64.4
2                                  9.0  64.6
3                                  9.0  64.8
4                                  9.0  64.9
5     104.0                        9.0  65.0
6                                  9.0  65.0
7     102.0                        9.1  65.0
8     101.0                        9.2  65.0
9                                  9.3  65.0
10                                 9.4  65.0
11                                 9.4  65.0
12                                 9.6  65.0
13                                 9.6  65.0
14                                 9.7  65.0
15                                 9.8  65.0
16                                 9.8  65.1
17                                 9.9  65.4
18                                10.0  65.5
19                                10.0  65.8
================================================================================
Displaying columns 31 to 40:
    fracture_present  kidney_stones_present l1_t_score  l2_t_score  \
0                 -1                      0       -0.9        -0.3
1                 -1                      0       -0.9        -0.3
2                 -1                      0       -0.8        -0.2
3                 -1                      0       -0.8        -0.1
4                 -1                      0       -0.8         0.1
5                 -1                      0       -0.8         0.2
6                  0                      0       -0.8         0.2
7                 -1                      0       -0.8         0.2
8                 -1                      0       -0.8         0.4
9                 -1                      0       -0.8         0.5
10                -1                      0       -0.7         0.5
11                -1                      0       -0.6         0.5
12                -1                      0       -0.5         0.7
13                -1                      0       -0.4         0.8
14                -1                      0       -0.4         0.9
15                -1                      0       -0.4         1.0
16                -1                      0       -0.3         1.0
17                 1                      0       -0.3         1.4
18                -1                      0       -0.2         1.4
19                -1                      0       -0.2         2.3

    l3_t_score l4_t_score  l1_z_score  l2_z_score  l3_z_score  l4_z_score
0         -0.5       -0.3         NaN         NaN         NaN         NaN
1         -0.5       -0.1         NaN         NaN         NaN         NaN
2         -0.4        0.0         NaN         NaN         NaN         NaN
3         -0.4        0.1         NaN         NaN         NaN         NaN
4         -0.3        0.1         NaN         NaN         NaN         NaN
5         -0.3        0.1         NaN         NaN         NaN         NaN
6         -0.2        0.1         NaN         NaN         NaN         NaN
7         -0.2        0.2         NaN         NaN         NaN         NaN
8         -0.1        0.2         NaN         NaN         NaN         NaN
9          0.1        0.3         NaN         NaN         NaN         NaN
10         0.1        0.3         NaN         NaN         NaN         NaN
11         0.2        0.3         NaN         NaN         NaN         NaN
12         0.2        0.6         NaN         NaN         NaN         NaN
13         0.2        0.6         NaN         NaN         NaN         NaN
14         0.2        0.9         NaN         NaN         NaN         NaN
15         0.2        1.2         NaN         NaN         NaN         NaN
16         0.3        1.3         NaN         NaN         NaN         NaN
17         0.3        1.9         NaN         NaN         NaN         NaN
18         0.3        1.9         NaN         NaN         NaN         NaN
19         0.6        2.0         NaN         NaN         NaN         NaN
================================================================================
Displaying columns 41 to 50:
   femoral_neck_z_score femoral_neck_t_score radius_z_score  radius_t_score  \
0                                                                       NaN
1                                                                       NaN
2                                                                       NaN
3                                                                       NaN
4                                                                       NaN
5                                                                       NaN
6                                                                       NaN
7                                                                       NaN
8                                                                       NaN
9                                                                       NaN
10                                                                      NaN
11                                                                      NaN
12                                                                      NaN
13                                                                      NaN
14                                                                      NaN
15                                                                      NaN
16                                                                      NaN
17                                                                      NaN
18                                                                      NaN
19                                                                      NaN

    l1_l4_t_score  femur_total_t_score  l1_l4_z_score  femur_total_z_score  \
0             NaN                  NaN            NaN                  NaN
1             NaN                  NaN            NaN                  NaN
2             NaN                  NaN            NaN                  NaN
3             NaN                  NaN            NaN                  NaN
4             NaN                  NaN            NaN                  NaN
5             NaN                  NaN            NaN                  NaN
6             NaN                  NaN            NaN                  NaN
7             NaN                  NaN            NaN                  NaN
8             NaN                  NaN            NaN                  NaN
9             NaN                  NaN            NaN                  NaN
10            NaN                  NaN            NaN                  NaN
11            NaN                  NaN            NaN                  NaN
12            NaN                  NaN            NaN                  NaN
13            NaN                  NaN            NaN                  NaN
14            NaN                  NaN            NaN                  NaN
15            NaN                  NaN            NaN                  NaN
16            NaN                  NaN            NaN                  NaN
17            NaN                  NaN            NaN                  NaN
18            NaN                  NaN            NaN                  NaN
19            NaN                  NaN            NaN                  NaN

    abdominal_pain  fatigue
0                1        1
1                1        1
2                1        1
3                1        1
4                1        1
5                1        1
6                1        1
7                1        1
8                1        1
9               -1        1
10              -1        1
11              -1        1
12              -1        1
13              -1        1
14              -1        1
15              -1        1
16              -1        1
17              -1        1
18              -1        1
19              -1        1
================================================================================
Displaying columns 51 to 60:
    myalgia  constipation  insomnia  polydipsia  polyuria  muscle_weakness  \
0         1             0         0          -1        -1               -1
1         1             0         0          -1        -1               -1
2         1             0         0          -1        -1               -1
3         1             0         0          -1        -1               -1
4         1             0         0          -1        -1               -1
5         1             0         0          -1        -1               -1
6         1             0         0          -1        -1               -1
7         1             0         0           1         1                1
8         1             0         0          -1        -1               -1
9         1             0         0          -1        -1               -1
10        1             0         0          -1        -1               -1
11        1             0         0          -1        -1               -1
12        1             0         0          -1        -1               -1
13        1             0         0          -1        -1               -1
14        1             0         0          -1        -1               -1
15        1             0         0          -1        -1               -1
16        1             0         0          -1        -1               -1
17        1             0         0          -1        -1               -1
18        1             0         0          -1        -1               -1
19        1             0         0          -1        -1               -1

    headache  nausea  amnesia  gallstones
0         -1      -1       -1          -1
1         -1      -1       -1          -1
2         -1      -1       -1          -1
3         -1      -1       -1          -1
4         -1      -1       -1          -1
5         -1      -1       -1          -1
6         -1      -1       -1          -1
7          1       1        1           0
8         -1      -1       -1          -1
9         -1      -1       -1          -1
10        -1      -1       -1          -1
11        -1      -1       -1          -1
12        -1      -1       -1          -1
13        -1      -1       -1          -1
14        -1       1       -1           0
15        -1      -1       -1          -1
16        -1      -1       -1          -1
17        -1      -1       -1          -1
18         1      -1       -1          -1
19        -1      -1       -1          -1
================================================================================
Displaying columns 61 to 70:
    nephrolithiasis  corrected_calcium_by_albumin  \
0                 1                          8.52
1                 1                          8.52
2                 1                          8.52
3                 1                          8.52
4                 1                          8.52
5                 1                          8.52
6                 1                          8.54
7                 1                          8.54
8                 1                          8.54
9                 1                          8.54
10                1                          8.54
11                1                          8.54
12                1                          8.54
13                1                          8.54
14                1                          8.56
15                1                          8.56
16                1                          8.56
17                1                          8.56
18                1                          8.56
19                1                          8.56

    serum_calcium_phosphorus_ratio pf_index alp_combined_with_cl_po4  \
0                         2.685714                               NaN
1                         2.685714                               NaN
2                         2.692893                               NaN
3                         2.693410                               NaN
4                         2.694444                               NaN
5                         2.694444                               NaN
6                         2.694444                               NaN
7                         2.695652   2178.0                      NaN
8                         2.702703                               NaN
9                         2.705882                               NaN
10                        2.705882                               NaN
11                        2.705882                               NaN
12                        2.710000                               NaN
13                        2.710526                               NaN
14                        2.714286                               NaN
15                        2.714286                               NaN
16                        2.728571                               NaN
17                        2.729730                               NaN
18                        2.735294                               NaN
19                        2.735294                               NaN

   parathyroid_scintigraphy       parathyroid_spect neck_ultrasound 4d_ct  \

In [16]:
#df.to_excel('hyperThyroidv1Outputv2.xlsx', index=False)