# Removing 2 columns pf_index and alp_combined as it contains null values

In [1]:
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import warnings

df = pd.read_csv("2024Nov_HT_Phase2.4.csv", encoding='latin-1')

In [2]:
# Print columns before dropping
print("Columns before dropping:", df.columns.tolist())

# Drop the specified columns
df = df.drop(columns=['alp_combined_with_cl_po4', 'pf_index'])

# Print columns after dropping
print("Columns after dropping:", df.columns.tolist())

Columns before dropping: ['aphp', 'nhph', 'tertiary_hp', 'secondary_hp', 'age', 'gender', 'height', 'weight', 'bmi', 'marital_status', 'tobacco', 'magnesium', 'alp', 'albumin', 'serum_calcium', 'ionized_calcium', 'serum_creatinine', 'gfr', 'phosphorus', 'urinary_calcium_24h', 'urinary_creatinine_24h', 'corrected_calcium_by_albumin', 'pth', 'urinary_phosphorus_24h', 'urinary_sodium_24h', 'total_protein', 'Triglycerides', 'ldl_cholesterol', 'total_cholesterol', 'ast', 'alt', 'ALP', 'ggt', 'bun', 'chlorine', 'serum_25_hydroxy_vitamin_d', 'fracture_present', 'kidney_stones_present', 'l1_t_score', 'l2_t_score', 'l3_t_score', 'l4_t_score', 'l1_z_score', 'l2_z_score', 'l3_z_score', 'l4_z_score', 'femoral_neck_z_score', 'femoral_neck_t_score', 'radius_z_score', 'radius_t_score', 'psychiatric_symptoms_present', 'abdominal_pain', 'fatigue', 'myalgia', 'constipation', 'insomnia', 'polydipsia', 'polyuria', 'muscle_weakness', 'headache', 'nausea', 'amnesia', 'gallstones', 'KIRIKVAR', 'nephrolithiasis', 'bone_specific_alp', 'serum_calcium_phosphorus_ratio', 'pf_index', 'alp_combined_with_cl_po4', 'third_surgery_pathology_report', 'fourth_surgery_pathology_report', 'triglycerides', 'hdl_cholesterol']
Columns after dropping: ['aphp', 'nhph', 'tertiary_hp', 'secondary_hp', 'age', 'gender', 'height', 'weight', 'bmi', 'marital_status', 'tobacco', 'magnesium', 'alp', 'albumin', 'serum_calcium', 'ionized_calcium', 'serum_creatinine', 'gfr', 'phosphorus', 'urinary_calcium_24h', 'urinary_creatinine_24h', 'corrected_calcium_by_albumin', 'pth', 'urinary_phosphorus_24h', 'urinary_sodium_24h', 'total_protein', 'Triglycerides', 'ldl_cholesterol', 'total_cholesterol', 'ast', 'alt', 'ALP', 'ggt', 'bun', 'chlorine', 'serum_25_hydroxy_vitamin_d', 'fracture_present', 'kidney_stones_present', 'l1_t_score', 'l2_t_score', 'l3_t_score', 'l4_t_score', 'l1_z_score', 'l2_z_score', 'l3_z_score', 'l4_z_score', 'femoral_neck_z_score', 'femoral_neck_t_score', 'radius_z_score', 'radius_t_score', 'psychiatric_symptoms_present', 'abdominal_pain', 'fatigue', 'myalgia', 'constipation', 'insomnia', 'polydipsia', 'polyuria', 'muscle_weakness', 'headache', 'nausea', 'amnesia', 'gallstones', 'KIRIKVAR', 'nephrolithiasis', 'bone_specific_alp', 'serum_calcium_phosphorus_ratio', 'third_surgery_pathology_report', 'fourth_surgery_pathology_report', 'triglycerides', 'hdl_cholesterol']

In [3]:
df.head()

,aphp,nhph,tertiary_hp,secondary_hp,age,gender,height,weight,bmi,marital_status,...,amnesia,gallstones,KIRIKVAR,nephrolithiasis,bone_specific_alp,serum_calcium_phosphorus_ratio,third_surgery_pathology_report,fourth_surgery_pathology_report,triglycerides,hdl_cholesterol
0,0,0,0,0,0,-1,0.0,0.0,0.0,0,...,-1,-1,0,-1,0,0,0,0,0,0
1,0,0,0,0,65,0,0.0,0.0,0.0,0,...,-1,-1,0,-1,0,0,0,0,0,0
2,0,0,0,0,0,-1,0.0,0.0,0.0,0,...,-1,-1,0,-1,0,0,0,0,0,0
3,0,0,0,0,0,-1,0.0,0.0,0.0,0,...,-1,-1,0,-1,0,0,0,0,0,0
4,0,1,0,0,40,1,162.0,82.0,0.0,0,...,-1,-1,0,-1,0,0,0,0,0,0

In [4]:
 df.to_excel('2024Nov_HT_Phase2.5.xlsx', index=False)